config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'    => 'static_pages#about'
  get 'status' => 'static_pages#status'
  get 'signup'  => 'users#new'
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def status
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Twitterへようこそ!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返す
  def full_title(page_title = '')
    base_title = "Twitter Copy"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Twitterについて", about_path %></li>
      <li><%= link_to "ヘルプ", help_path %></li>
      <li><%= link_to "ステータス", status_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse bg-lightBlue">
  <div class="container">
    <div class="text-center text-white">
      <h1>「いま」を見つけよう</h1>
    </div>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム",   root_path %></li>
        <li><%= link_to "ログイン", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%# pluralizeは数字(引数1)と文字列(引数2)をつなげるメソッド(複数系にも対応) %>
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  これはRuby on railsのサンプルを参考に、Twitterのページを模倣したものです
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  本家のTwitterは以下↓<br>
  <a href="https://twitter.com/">Twitter</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center text-white bg-lightBlue create-account">
  <h3>
      Twitterを使ってみよう
  </h3>
  
  <h4>
      登録してあなただけのタイムライン<br>
      を作りましょう
  </h4>

  <%= link_to "アカウント作成", signup_path, class: "btn btn-lg btn-default text-lightBlue" %>
</div>

app/views/static_pages/status.html.erb
<div class="status">
  <h1>
        Status
  </h1>
  <div class="top-panel">
    <div class="panel panel-default">
      <div class="panel-body">
        <p class="leftText"><strong>All Systems Operational</strong></p>
        <p class="rightText">Updated a month ago</p>
      </div>
    </div>
  </div>
  <div class="bottom-panel">
    <div class="panel panel-default">
      <div class="panel-body">
        <p class="leftText"><strong>Twitter</strong></p>
        <p class="rightText">Operational</p>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="new">
  <h1>Twitterを使ってみよう</h1>
  
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
      
        <%= f.label :name, "呼び名(ニックネームでも可)"%>
        <%= f.text_field :name, class: 'form-control' %>
  
        <%= f.label :email, "メールアドレス"%>
        <%= f.email_field :email, class: 'form-control' %>
  
        <%= f.label :password, "パスワード"%>
        <%= f.password_field :password, class: 'form-control' %>
  
        <%= f.label :password_confirmation, "パスワード(確認)" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
  
        <%= f.submit "アカウント作成", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<br><br><br>
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>